config/routes.rb
Rails.application.routes.draw do
  resources :farms
  devise_for :users
  root to: "home#index"
  get "/farms/:id/:id2", to: "farms#show", as: "alert"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/farm.rb
class Farm < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :farms, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        '/farms'
      end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    @farms = Farm.all 
  end

  def new
    @farm = Farm.new
  end

  def show
    @farm = Farm.find(params[:id]) 
    
   end

  def edit
    @farm = Farm.find(params[:id])
  end

  def create
    @user = current_user
    @farm = @user.farms.create(farm_params)  
    redirect_to farms_path
  end
  def destroy
    
    @farm = Farm.find(params[:id])
    @farm.destroy
    redirect_to farms_path
  end
  def update
    @user = current_user
    @farm = @user.farms.find(params[:id])
    @farm.update(farm_params)
    redirect_to farms_path
  end
  private
  def farm_params
      params.require(:farm).permit(:name, :price, :location, :image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
    def index
      
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/farms/_form.html.erb
<hr>
<%= form_for :farm do |f|%>
    <label>Name: </label>
    <%=  f.name%> 
    <br>
    <label>Price: </label>
    <%= f.price %> 
    <br>
    <label>Location: </label>
    <%= f.location %> 
    <br>
     <label>image: </label>
    <img style="width:150px;height:150px"src="<%= f.image %>">
   <hr>
   <%end%>

app/views/farms/edit.html.erb
<h1> Edit <%= @farm.name %></h1>
<%= form_for @farm, url: {action: "update"} do |f| %>
    <%= f.label :name, 'Name' %><br>
    <%= f.text_field :name %><br><br>
    <%= f.label :price, 'Price' %><br>
    <%=f.text_field :price %><br><br>
    <%= f.label :location, 'Location' %><br> 
    <%=f.text_field :location %><br><br> 
    <%= f.label :image, 'Image' %><br> 
    <%=f.text_field :image %><br><br> 
   <%= f.submit "Submit" %> 
<% end %>

app/views/farms/index.html.erb
<div class= "container">
    <h1 class="display-3">Hello  <%= @user.email %></h1>
    <h3><%=  link_to 'Add A New Farm', new_farm_path %></h3>
    <hr>

 <% @farms.each do |farm|%>  
 
    <tr>
    <td><img class="img-thumbnail" src=<%=farm.image%> height="400" width="400"></td><br>
    <td><%= link_to farm.name, farm_path(farm) , class: "bg-dark text-danger"%></td><br>
    <td><%=farm.price%> SR</td><br>
    <td><%=farm.location%></td><br>
    </tr>
    <% end %>
  
 
</div>

  

app/views/farms/new.html.erb
<div class= "container">

<h2> ADD NEW FARM</h2>
<%= form_for @farm, url: {action: "create"} do |f|%>
 <div class="form-group">
    <%= f.label :name%><br>
    <%= f.text_field :name%>
    <br>
    </div>
    <div class="form-group">
    <%= f.label :price%><br>
    <%= f.text_field :price%>RS
    <br>
    </div>
    <div class="form-group">
    <%= f.label :location%><br>
    <%= f.text_field :location%>
    <br>
    </div>
    <div class="form-group">
    <%= f.label :image%><br>
    <%= f.text_field :image%>
    <br>
    </div>
   
    <%= f.submit "Save"%>
<% end %>
</div>

app/views/farms/show.html.erb
<div class= "container">
<% if params[:id2] == "1" %>
    <script>
        alert("You Are rented this farm")
    </script>
<% end %>
<h1><img img class="img-thumbnail" src=<%=@farm.image%> height="150" width="400"></h1>

<h1><%= @farm.name  %></h1>
<h1><%= @farm.price %> SR</h1>
<h1><%= @farm.location  %></h1>
<% if current_user.id == @farm.user_id %>
    <%= link_to 'Edit', edit_farm_path(@farm), class: "alert alert-primary" %> 
    <%= link_to 'Delete', farm_path(@farm), method: :delete , class: "alert alert-primary"%>
<%else%>
<%= link_to 'Rent', alert_path(@farm, 1) , class: "alert alert-primary"%> 
    
<%end%>
</div>

app/views/home/index.html.erb
<div class= "container">
<h1 class="display-3">Hello Everyone<h1><br>
<p class="display-3">This is website help you to rent the farms in Sadia Arabia </p><br>
<%= link_to 'ENTER HERE', new_user_session_path(@farm), class: "bg-dark"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project2</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
 integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <link href='https://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700,400italic|Montserrat:400,700|Cardo:400italic|Advent+Pro:100' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>

  <body style="background-image: url('https://images.pexels.com/photos/1090552/pexels-photo-1090552.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');">
  <div >
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= farms_path%>">FARM</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= new_farm_path%>">ADD <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
       </ul>
    <form class="form-inline my-2 my-lg-0">
<% if(user_signed_in?)%>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete%>
    <%= link_to "Update my Acount", edit_user_registration_path%>
<% end %>
 </form>
  </div>
</nav>


        <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" 
integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    
    <%= yield %>
</div>
  </body>
</html>